-- CreateTable
CREATE TABLE `USUARIO` (
    `cpf` INTEGER NOT NULL,
    `ts_criacao` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `ts_alteracao` DATETIME(3) NOT NULL,
    `nome` VARCHAR(255) NOT NULL,
    `email` VARCHAR(100) NOT NULL,
    `celular` INTEGER NOT NULL,
    `data_nasc` DATETIME(3) NOT NULL,

    UNIQUE INDEX `USUARIO_email_key`(`email`),
    PRIMARY KEY (`cpf`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `ENDERECO` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `rua` VARCHAR(100) NOT NULL,
    `numero` INTEGER NOT NULL,
    `bairro` VARCHAR(100) NOT NULL,
    `cep` INTEGER NOT NULL,
    `cpf` INTEGER NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `PAGAMENTO` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `tipo` VARCHAR(50) NOT NULL,

    UNIQUE INDEX `PAGAMENTO_tipo_key`(`tipo`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `MODELO` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `tipo` VARCHAR(50) NOT NULL,

    UNIQUE INDEX `MODELO_tipo_key`(`tipo`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `NUM_SERIE_MODELO` (
    `numero_serie` INTEGER NOT NULL,
    `id_modelo` INTEGER NOT NULL,

    PRIMARY KEY (`numero_serie`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `CATEGORIA` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `tipo` VARCHAR(50) NOT NULL,

    UNIQUE INDEX `CATEGORIA_tipo_key`(`tipo`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `SUBCATEGORIA` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `tipo` VARCHAR(50) NOT NULL,

    UNIQUE INDEX `SUBCATEGORIA_tipo_key`(`tipo`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `PRODUTO` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `ts_criacao` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `ts_alteracao` DATETIME(3) NOT NULL,
    `fabricante` VARCHAR(150) NOT NULL,
    `preco_base` INTEGER NOT NULL,
    `estoque` INTEGER NOT NULL,
    `id_modelo` INTEGER NOT NULL,
    `id_categoria` INTEGER NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `SUBCATEGORIA_PRODUTO` (
    `id_produto` INTEGER NOT NULL,
    `id_subcategoria` INTEGER NOT NULL,

    PRIMARY KEY (`id_produto`, `id_subcategoria`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `PEDIDO` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `desconto` INTEGER NOT NULL,
    `total` INTEGER NOT NULL,
    `ts_criacao` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `cpf` INTEGER NULL,
    `id_endereco` INTEGER NULL,
    `id_pagamento` INTEGER NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `PEDIDO_PRODUTO` (
    `quantidade` INTEGER NOT NULL,
    `id_produto` INTEGER NOT NULL,
    `id_pedido` INTEGER NOT NULL,

    PRIMARY KEY (`id_produto`, `id_pedido`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `ENDERECO` ADD CONSTRAINT `ENDERECO_cpf_fkey` FOREIGN KEY (`cpf`) REFERENCES `USUARIO`(`cpf`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `NUM_SERIE_MODELO` ADD CONSTRAINT `NUM_SERIE_MODELO_id_modelo_fkey` FOREIGN KEY (`id_modelo`) REFERENCES `MODELO`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `PRODUTO` ADD CONSTRAINT `PRODUTO_id_modelo_fkey` FOREIGN KEY (`id_modelo`) REFERENCES `MODELO`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `PRODUTO` ADD CONSTRAINT `PRODUTO_id_categoria_fkey` FOREIGN KEY (`id_categoria`) REFERENCES `CATEGORIA`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `SUBCATEGORIA_PRODUTO` ADD CONSTRAINT `SUBCATEGORIA_PRODUTO_id_produto_fkey` FOREIGN KEY (`id_produto`) REFERENCES `PRODUTO`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `SUBCATEGORIA_PRODUTO` ADD CONSTRAINT `SUBCATEGORIA_PRODUTO_id_subcategoria_fkey` FOREIGN KEY (`id_subcategoria`) REFERENCES `SUBCATEGORIA`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `PEDIDO` ADD CONSTRAINT `PEDIDO_cpf_fkey` FOREIGN KEY (`cpf`) REFERENCES `USUARIO`(`cpf`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `PEDIDO` ADD CONSTRAINT `PEDIDO_id_endereco_fkey` FOREIGN KEY (`id_endereco`) REFERENCES `ENDERECO`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `PEDIDO` ADD CONSTRAINT `PEDIDO_id_pagamento_fkey` FOREIGN KEY (`id_pagamento`) REFERENCES `PAGAMENTO`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `PEDIDO_PRODUTO` ADD CONSTRAINT `PEDIDO_PRODUTO_id_produto_fkey` FOREIGN KEY (`id_produto`) REFERENCES `PRODUTO`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `PEDIDO_PRODUTO` ADD CONSTRAINT `PEDIDO_PRODUTO_id_pedido_fkey` FOREIGN KEY (`id_pedido`) REFERENCES `PEDIDO`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;
